// export const REQUEST_PROGRESS_BAR_DATA = 'REQUEST_PROGRESS_BAR_DATA';
// export const RECEIVE_PROGRESS_BAR_DATA = 'RECEIVE_PROGRESS_BAR_DATA';
// export const RECEIVE_PROGRESS_BAR_ERROR = 'RECEIVE_PROGRESS_BAR_ERROR';

export const REQUEST_API_ACCESS_DATA = 'REQUEST_API_ACCESS_DATA';
export const RECEIVE_API_ACCESS_DATA = 'RECEIVE_API_ACCESS_DATA';
export const RECEIVE_API_ACCESS_ERROR = 'RECEIVE_API_ACCESS_ERROR';

export const REQUEST_ARCHIVE_DATA = 'REQUEST_ARCHIVE_DATA';
export const RECEIVE_ARCHIVE_DATA = 'RECEIVE_ARCHIVE_DATA';
export const RECEIVE_ARCHIVE_ERROR = 'RECEIVE_ARCHIVE_ERROR';

export const REQUEST_FEATURED_OPTIONS_DATA = 'REQUEST_FEATURED_OPTIONS_DATA';
export const RECEIVE_FEATURED_OPTIONS_DATA = 'RECEIVE_FEATURED_OPTIONS_DATA';
export const RECEIVE_FEATURED_OPTIONS_ERROR = 'RECEIVE_FEATURED_OPTIONS_ERROR';

export const REQUEST_FEATURED_CAROUSEL_DATA = 'REQUEST_FEATURED_CAROUSEL_DATA';
export const RECEIVE_FEATURED_CAROUSEL_DATA = 'RECEIVE_FEATURED_CAROUSEL_DATA';
export const RECEIVE_FEATURED_CAROUSEL_ERROR = 'RECEIVE_FEATURED_CAROUSEL_ERROR';

export const REQUEST_BLOG_FEATURED_CAROUSEL_DATA = 'REQUEST_BLOG_FEATURED_CAROUSEL_DATA';
export const RECEIVE_BLOG_FEATURED_CAROUSEL_DATA = 'RECEIVE_BLOG_FEATURED_CAROUSEL_DATA';
export const RECEIVE_BLOG_FEATURED_CAROUSEL_ERROR = 'RECEIVE_BLOG_FEATURED_CAROUSEL_ERROR';

export const REQUEST_BLOG_FEATURED_SECTIONS_DATA = 'REQUEST_BLOG_FEATURED_SECTIONS_DATA';
export const RECEIVE_BLOG_FEATURED_SECTIONS_DATA = 'RECEIVE_BLOG_FEATURED_SECTIONS_DATA';
export const RECEIVE_BLOG_FEATURED_SECTIONS_ERROR = 'RECEIVE_BLOG_FEATURED_SECTIONS_ERROR';

export const REQUEST_SHOW_FEATURED_CAROUSEL_DATA = 'REQUEST_SHOW_FEATURED_CAROUSEL_DATA';
export const RECEIVE_SHOW_FEATURED_CAROUSEL_DATA = 'RECEIVE_SHOW_FEATURED_CAROUSEL_DATA';
export const RECEIVE_SHOW_FEATURED_CAROUSEL_ERROR = 'RECEIVE_SHOW_FEATURED_CAROUSEL_ERROR';

export const REQUEST_SHOW_FEATURED_SECTIONS_DATA = 'REQUEST_SHOW_FEATURED_SECTIONS_DATA';
export const RECEIVE_SHOW_FEATURED_SECTIONS_DATA = 'RECEIVE_SHOW_FEATURED_SECTIONS_DATA';
export const RECEIVE_SHOW_FEATURED_SECTIONS_ERROR = 'RECEIVE_SHOW_FEATURED_SECTIONS_ERROR';

export const REQUEST_DOTSTUDIOPRO_CHANNELS_DATA = 'REQUEST_DOTSTUDIOPRO_CHANNELS_DATA';
export const RECEIVE_DOTSTUDIOPRO_CHANNELS_DATA = 'RECEIVE_DOTSTUDIOPRO_CHANNELS_DATA';
export const RECEIVE_DOTSTUDIOPRO_CHANNELS_ERROR = 'RECEIVE_DOTSTUDIOPRO_CHANNELS_ERROR';

export const REQUEST_DOTSTUDIOPRO_CHANNEL_DATA = 'REQUEST_DOTSTUDIOPRO_CHANNEL_DATA';
export const RECEIVE_DOTSTUDIOPRO_CHANNEL_DATA = 'RECEIVE_DOTSTUDIOPRO_CHANNEL_DATA';
export const RECEIVE_DOTSTUDIOPRO_CHANNEL_ERROR = 'RECEIVE_DOTSTUDIOPRO_CHANNEL_ERROR';

export const REQUEST_BIO_DATA = 'REQUEST_BIO_DATA';
export const RECEIVE_BIO_DATA = 'RECEIVE_BIO_DATA';
export const RECEIVE_BIO_ERROR = 'RECEIVE_BIO_ERROR';

export const REQUEST_IVP_VIDEO = 'REQUEST_IVP_VIDEO';
export const RECEIVE_IVP_VIDEO = 'RECEIVE_IVP_VIDEO';
export const RECEIVE_IVP_VIDEO_ERROR = 'RECEIVE_IVP_VIDEO_ERROR';

export const REQUEST_CLEAN_IVP = 'REQUEST_CLEAN_IVP';
export const RECEIVE_CLEAN_IVP = 'RECEIVE_CLEAN_IVP';

export const REQUEST_CLEAR_IVP_CONTENT = 'REQUEST_CLEAR_IVP_CONTENT';
export const RECEIVE_CLEAR_IVP_CONTENT = 'RECEIVE_CLEAR_IVP_CONTENT';

export const REQUEST_HERO_DATA = 'REQUEST_HERO_DATA';
export const RECEIVE_HERO_DATA = 'RECEIVE_HERO_DATA';
export const RECEIVE_HERO_ERROR = 'RECEIVE_HERO_ERROR';

export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export const RECEIVE_SEARCH_ERROR = 'RECEIVE_SEARCH_ERROR';

export const REQUEST_SEARCH_RESET = 'REQUEST_SEARCH_RESET';
export const RECEIVE_SEARCH_RESET = 'RECEIVE_SEARCH_RESET';
export const RECEIVE_SEARCH_RESET_ERROR = 'RECEIVE_SEARCH_RESET_ERROR';

export const REQUEST_POST_DATA = 'REQUEST_POST_DATA';
export const RECEIVE_POST_DATA = 'RECEIVE_POST_DATA';
export const RECEIVE_POST_DATA_ERROR = 'RECEIVE_POST_DATA_ERROR';
export const CLEAN_POST_DATA = 'CLEAN_POST_DATA';

export const REQUEST_WATCH_RAILS = 'REQUEST_WATCH_RAILS';
export const RECEIVE_WATCH_RAILS_DATA = 'RECEIVE_WATCH_RAILS_DATA';
export const RECEIVE_WATCH_RAILS_ERROR = 'RECEIVE_WATCH_RAILS_ERROR';

export const REQUEST_WATCH_RAIL_PLAYLIST = 'REQUEST_WATCH_RAIL_PLAYLIST';
export const RECEIVE_WATCH_RAIL_PLAYLIST_DATA = 'RECEIVE_WATCH_RAIL_PLAYLIST_DATA';
export const RECEIVE_WATCH_RAIL_PLAYLIST_ERROR = 'RECEIVE_WATCH_RAIL_PLAYLIST_ERROR';

export const REQUEST_RANDOM_POSTS_DATA = 'REQUEST_RANDOM_POSTS_DATA';
export const RECEIVE_RANDOM_POSTS_DATA = 'RECEIVE_RANDOM_POSTS_DATA';
export const RECEIVE_RANDOM_POSTS_ERROR = 'RECEIVE_RANDOM_POSTS_ERROR';
export const REQUEST_CLEAR_RANDOM = 'REQUEST_CLEAR_RANDOM';
export const RECEIVE_CLEAR_RANDOM = 'RECEIVE_CLEAR_RANDOM';
export const RECEIVE_CLEAN_RANDOM_ERROR = 'RECEIVE_CLEAN_RANDOM_ERROR';

export const REQUEST_COLLAGE_DATA = 'REQUEST_COLLAGE_DATA';
export const RECEIVE_COLLAGE_DATA = 'RECEIVE_COLLAGE_DATA';
export const RECEIVE_COLLAGE_ERROR = 'RECEIVE_COLLAGE_ERROR';

export const REQUEST_INSTAGRAM_DATA = 'REQUEST_INSTAGRAM_DATA';
export const RECEIVE_INSTAGRAM_DATA = 'RECEIVE_INSTAGRAM_DATA';
export const RECEIVE_INSTAGRAM_ERROR = 'RECEIVE_INSTAGRAM_ERROR';

export const REQUEST_MAILCHIMP_SUBSCRIBE = 'REQUEST_MAILCHIMP_SUBSCRIBE';
export const RECEIVE_MAILCHIMP_SUBSCRIBE = 'RECEIVE_MAILCHIMP_SUBSCRIBE';
export const RECEIVE_MAILCHIMP_ERROR = 'RECEIVE_MAILCHIMP_ERROR';
